name = "FibErrThresh"
uuid = "5a702e01-c761-448f-bf74-21865a8cdff7"
version = "0.1.0"
authors = ["nmaserang <nmaserang@berkeley.edu>"]

[deps]
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArraysBase = "0d5efcca-f356-4864-8770-e1ed8d78f208"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
GraphRecipes = "0.5.15"
Graphs = "1.13.1"
ITensors = "0.9.14"
MetaGraphsNext = "0.7.4"
Plots = "1.41.1"
SparseArraysBase = "0.7.7"
TensorKitSectors = "0.3.2"
Test = "1.11.0"
